# Generated by Django 6.0.7 on 2026-08-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
