# Generated by Django 6.0.7 on 2026-09-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.CharField(max_length=150),
        ),
    ]
