# Generated by Django 6.0.7 on 2026-09-02 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.course'),
        ),
    ]
